### ISSUE TITLE
When I login, I can't go back to the homepage, I can't see the videos that others have posted on the platform 

### ISSUE THREAD

**Issue by unicodeveloper** [andela-vdugeri/learner-tube#6]
I am stuck on the dashboard for Life. When I click Tubr or videos, it still doesnt redirect me to the homepage, it keeps me on the dashboard. Why is that? I am helpless here. Someone please save me!

You need to fix this ASAP!

<img width="1280" alt="screen shot 2015-10-26 at 8 05 19 am" src="https://cloud.githubusercontent.com/assets/2946769/10723180/80e6f168-7bb8-11e5-977f-484e1438b8c1.png">

**Comment by andela-vdugeri** [comment]
LOL. Verem to the rescue
